### PR TITLE
Make compatible with Broadway v2.1

### PR DESCRIPTION
**Pull request by karpilin**
- update composer dependency
- match Broadway\Serializer interface signature

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Looks good to me, but I'd prefer having a Travis setup that has two test runs, one with Broadway 1 and one with Broadway 2 (because as it is right now, we have no way to tell that everything works fine with Broadway 1).

**Comment by matthiasnoback** [comment]
Is that something you can work on?

**Comment by karpilin** [comment]
> Is that something you can work on?

Sure! I'll see what I can do

**Comment by matthiasnoback** [comment]
Nice! I think it's a bit too much to still test it with all those PHP versions, so maybe we can pick one older version to run with Broadway 1 and the latest version to run with Broadway 2? Something like that?

**Comment by karpilin** [comment]
> Nice! I think it's a bit too much to still test it with all those PHP versions, so maybe we can pick one older version to run with Broadway 1 and the latest version to run with Broadway 2? Something like that?

Actually, because Broadway v2 requires php71 or above, for builds on php70 composer will automatically pick Broadway v1 as a dependency.

I'll keep a more explicit separation using jobs.

**Comment by matthiasnoback** [comment]
Nice work, I'll release now :)

**Pull request merged**
